version: 2.1
orbs:
  node: circleci/node@5
  codecov: codecov/codecov@3
jobs:
  test:
    docker:
      - image: cimg/node:current
      - image: linuxserver/transmission
        environment:
          PUID: "1000"
          PGID: "1000"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:ci
      - store_test_results:
          path: ./junit.xml
      - store_test_results:
          path: ./reports
      - codecov/upload
  release:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          filters:
            branches:
              only:
                - master
          context:
            - npm
          requires:
            - test
