name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      transmission:
        image: lscr.io/linuxserver/transmission:latest
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/UTC
        ports:
          - '9091:9091'
          - '51413:51413'
          - '51413:51413/udp'
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v5

      # https://github.com/wyvox/action-setup-pnpm
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 24

      - name: lint
        run: pnpm run lint

      - name: test
        run: pnpm run test:ci

      # https://github.com/codecov/codecov-action
      - name: coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
